// PNG → 무손실 WebP 변환. 원본 PNG는 그대로 두고, 픽셀이 완전히 같고 더 작은 WebP만 남긴다.
// 사용법: node scripts/convert-webp.mjs            전체 변환 + assets/js/webp-manifest.js 갱신
//         node scripts/convert-webp.mjs --sample 3 폴더별 앞 3장만 변환 (manifest는 건드리지 않음)
import { readdir, stat, unlink, writeFile } from 'node:fs/promises';
import { availableParallelism } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const folders = ['character-art', 'lightcone-art', 'characters', 'lightcones'];
const manifestPath = path.join(root, 'assets/js/webp-manifest.js');
const sampleIndex = process.argv.indexOf('--sample');
const sample = sampleIndex === -1 ? 0 : Number(process.argv[sampleIndex + 1]) || 3;
const concurrency = Math.max(1, Math.min(4, availableParallelism() - 1));

async function rawPixels(file) {
    const { data, info } = await sharp(file).ensureAlpha().raw({ depth: 'uchar' }).toBuffer({ resolveWithObject: true });
    return { data, info };
}

async function pixelsEqual(pngFile, webpFile) {
    const meta = await sharp(pngFile).metadata();
    if (meta.depth !== 'uchar' && meta.depth !== undefined) return false; // 16비트 PNG는 WebP(8비트)로 똑같이 만들 수 없음
    const [a, b] = await Promise.all([rawPixels(pngFile), rawPixels(webpFile)]);
    return a.info.width === b.info.width && a.info.height === b.info.height && a.data.equals(b.data);
}

async function convert(folder, name) {
    const png = path.join(root, 'assets', folder, name);
    const webp = png.replace(/\.png$/, '.webp');
    const pngStat = await stat(png);
    const existing = await stat(webp).catch(() => null);
    if (existing && existing.mtimeMs >= pngStat.mtimeMs) {
        return { folder, name, png: pngStat.size, webp: existing.size, status: existing.size < pngStat.size ? 'webp' : 'png', skipped: true };
    }
    await sharp(png).webp({ lossless: true, effort: 6, exact: true }).toFile(webp);
    const webpSize = (await stat(webp)).size;
    if (!(await pixelsEqual(png, webp))) {
        await unlink(webp);
        return { folder, name, png: pngStat.size, webp: pngStat.size, status: 'mismatch' };
    }
    if (webpSize >= pngStat.size) {
        await unlink(webp);
        return { folder, name, png: pngStat.size, webp: pngStat.size, status: 'png' };
    }
    return { folder, name, png: pngStat.size, webp: webpSize, status: 'webp' };
}

async function runPool(tasks) {
    const results = [];
    let next = 0;
    let done = 0;
    await Promise.all(Array.from({ length: concurrency }, async () => {
        while (next < tasks.length) {
            const task = tasks[next++];
            results.push(await task());
            done++;
            if (done % 10 === 0 || done === tasks.length) process.stdout.write(`\r${done}/${tasks.length} 처리`);
        }
    }));
    process.stdout.write('\n');
    return results;
}

const mb = bytes => (bytes / 1024 / 1024).toFixed(1);
const tasks = [];
for (const folder of folders) {
    const names = (await readdir(path.join(root, 'assets', folder))).filter(name => name.endsWith('.png')).sort();
    for (const name of sample ? names.slice(0, sample) : names) tasks.push(() => convert(folder, name));
}

const results = await runPool(tasks);

console.log('\n폴더            파일  변환 전(MB)  변환 후(MB)  절감');
for (const folder of folders) {
    const rows = results.filter(row => row.folder === folder);
    const before = rows.reduce((sum, row) => sum + row.png, 0);
    const after = rows.reduce((sum, row) => sum + Math.min(row.png, row.webp), 0);
    console.log(`${folder.padEnd(15)} ${String(rows.length).padStart(4)}  ${mb(before).padStart(11)}  ${mb(after).padStart(11)}  ${(100 - after / before * 100).toFixed(1)}%`);
}
const mismatched = results.filter(row => row.status === 'mismatch');
const keptPng = results.filter(row => row.status === 'png');
console.log(`\n픽셀 불일치(WebP 삭제): ${mismatched.length}개${mismatched.length ? ' — ' + mismatched.map(row => `${row.folder}/${row.name}`).join(', ') : ''}`);
console.log(`PNG가 더 작아 PNG 유지: ${keptPng.length}개${keptPng.length ? ' — ' + keptPng.map(row => `${row.folder}/${row.name}`).join(', ') : ''}`);

if (!sample) {
    const manifest = Object.fromEntries(folders.map(folder => [folder, results
        .filter(row => row.folder === folder && row.status === 'webp')
        .map(row => row.name.replace(/\.png$/, ''))
        .sort()]));
    await writeFile(manifestPath, `// Generated by scripts/convert-webp.mjs. 무손실 WebP가 있는 이미지 id 목록.\nglobalThis.HonkaiWebpManifest = ${JSON.stringify(manifest)};\n`);
    console.log(`\nmanifest 저장: ${path.relative(root, manifestPath)}`);
}
