import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=fileURLToPath(new URL('../',import.meta.url));
const files=['index.html','manifest.webmanifest','assets/favicon.svg'];
for(const dir of ['assets/js','assets/css','assets/characters','assets/lightcones','assets/icons','assets/paths']) {
    for(const file of await fs.readdir(path.join(root,dir))) if(/\.(js|css|png|svg|webp)$/.test(file)) files.push(`${dir}/${file}`);
}
const hash=createHash('sha256');for(const file of files) hash.update(await fs.readFile(path.join(root,file)));
const revision=hash.digest('hex').slice(0,12);
await fs.writeFile(path.join(root,'sw.js'),`// Generated by scripts/generate-pwa.mjs; run after editing shell assets.
const scopedPrefix='honkai-tools-'+new URL(self.registration.scope).pathname.replace(/[^a-z0-9]/gi,'_')+'-';
const CACHE=scopedPrefix+${JSON.stringify(revision)};
const CORE=${JSON.stringify(files)};
self.addEventListener('install',event=>event.waitUntil((async()=>{
 const cache=await caches.open(CACHE);
 for(let i=0;i<CORE.length;i+=16) await cache.addAll(CORE.slice(i,i+16).map(p=>new Request(new URL(p,self.registration.scope),{cache:'reload'})));
})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 for(const name of await caches.keys()) if(name.startsWith(scopedPrefix)&&name!==CACHE) await caches.delete(name);
 await self.clients.claim();
})()));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url),scope=new URL(self.registration.scope);
 if(event.request.method!=='GET'||url.origin!==scope.origin||!url.pathname.startsWith(scope.pathname)) return;
 const relative=url.pathname.slice(scope.pathname.length);
 if(event.request.mode==='navigate') {
  event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(new URL('index.html',scope).href))||fetch(event.request)));return;
 }
 if(!relative.startsWith('assets/')&&!CORE.includes(relative))return;
 event.respondWith(caches.open(CACHE).then(async cache=>{
  const saved=await cache.match(event.request);if(saved)return saved;
  const response=await fetch(event.request);
  // Large warp artwork, audio and reference files remain online-only.
  if(response.ok&&CORE.includes(relative)&&!url.search)await cache.put(event.request,response.clone());
  return response;
 }));
});
`);
console.log(`PWA shell ${revision}: ${files.length} assets`);
